FROM accent/pyenv:latest

# Copy the application code to the container:
RUN mkdir /code/
WORKDIR /code/
ADD . /code/

# Docker environment variables:
ENV TOX_PY27=2.7.15 \
    TOX_PY34=3.4.8 \
    TOX_PY35=3.5.5 \
    TOX_PY36=3.6.5

# set pyenv local versions
RUN pyenv local $TOX_PY27 $TOX_PY34 $TOX_PY35 $TOX_PY36

# Install dependencies
RUN pip install --upgrade tox codecov

# Start tox:
CMD ["tox", "-v"]