# Generated by Django 4.1.3 on 2023-02-23 20:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailstreamforms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_advancedformsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('form', wagtail.blocks.StructBlock([('form', wagtailstreamforms.blocks.FormChooserBlock()), ('form_action', wagtail.blocks.CharBlock(help_text='The form post action. "" or "." for the current page or a url', required=False)), ('form_reference', wagtailstreamforms.blocks.InfoBlock(help_text='This form will be given a unique reference once saved', required=False))]))], use_json_field=True),
        ),
    ]
