# Generated by Django 2.1.4 on 2019-01-10 10:17

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_advancedformsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedformsetting',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advancedformsetting',
            name='to_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
