# Generated by Django 5.0.13 on 2025-03-25 09:13

import wagtail.blocks
import wagtail.fields
import wagtailstreamforms.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_advancedformsetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", wagtail.blocks.RichTextBlock()),
                    (
                        "form",
                        wagtail.blocks.StructBlock(
                            [
                                ("form", wagtailstreamforms.blocks.FormChooserBlock()),
                                (
                                    "form_action",
                                    wagtail.blocks.CharBlock(
                                        help_text='The form post action. "" or "." for the current page or a url',
                                        required=False,
                                    ),
                                ),
                                (
                                    "form_reference",
                                    wagtailstreamforms.blocks.InfoBlock(
                                        help_text="This form will be given a unique reference once saved",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
