# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailstreamforms', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
        ('example', '0002_auto_20171012_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleForm',
            fields=[
                ('baseform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailstreamforms.BaseForm')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailstreamforms.baseform',),
        ),
        migrations.CreateModel(
            name='ExampleFormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit time')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailstreamforms.BaseForm')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form submission',
                'ordering': ['-submit_time'],
                'abstract': False,
            },
        ),
    ]
