# Generated by Django 2.0.3 on 2018-03-15 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_auto_20180130_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampleformsubmission',
            options={'ordering': ['-submit_time'], 'verbose_name': 'Form submission'},
        ),
        migrations.AlterField(
            model_name='exampleformsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailstreamforms.BaseForm', verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='exampleformsubmission',
            name='form_data',
            field=models.TextField(verbose_name='Form data'),
        ),
        migrations.AlterField(
            model_name='exampleformsubmission',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='exampleformsubmission',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submit time'),
        ),
    ]
