# Generated by Django 2.0.4 on 2018-04-28 07:13

from django.db import migrations
import wagtailstreamforms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='process_form_submission_hooks',
            field=wagtailstreamforms.fields.HookSelectField(default=[], blank=True),
            preserve_default=False,
        ),
    ]
