# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailstreamforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseform',
            name='post_redirect_page',
            field=models.ForeignKey(blank=True, help_text='The page to redirect to after a successful submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
