# Generated by Django 2.2.6 on 2019-11-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("wagtailstreamforms", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="form",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailcore.Site",
            ),
        )
    ]
