# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0002_baseform_post_redirect_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseform',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used to identify the form in template tags', max_length=255, null=True),
        ),
    ]
