# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0003_baseform_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseform',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='Used to identify the form in template tags', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
