# Generated by Django 4.2.20 on 2025-08-09 21:48

from django.db import migrations, connection

def add_custom_form_fields(apps, schema_editor):
    """
    Adds the success_title and error_title columns to the Form table
    only if they do not already exist.
    """
    Form = apps.get_model('wagtailstreamforms', 'Form')
    table_name = Form._meta.db_table

    with connection.cursor() as cursor:
        # Use a list to store columns to check and add
        columns_to_add = {
            'error_title': "VARCHAR(64) DEFAULT 'Achtung! Bitte korrigieren Sie die Formfehler' NULL",
            'success_title': "VARCHAR(64) DEFAULT 'Vielen Dank für Ihren Beitrag' NULL"
        }

        # Get existing columns for the table
        existing_columns = [col.name for col in connection.introspection.get_table_description(cursor, table_name)]

        for column_name, column_definition in columns_to_add.items():
            if column_name not in existing_columns:
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_definition}")

class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0003_alter_form_fields'),
    ]

    operations = [
        migrations.RunPython(add_custom_form_fields, migrations.RunPython.noop),
    ]
