# Generated by Django 4.2.20 on 2025-08-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0003_alter_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='error_title',
            field=models.CharField(default='Achtung! Bitte korrigieren Sie die Formfehler', help_text='An optional error title to show when the form has validation errors', max_length=64, null=True, verbose_name='Error Title'),
        ),
        migrations.AddField(
            model_name='form',
            name='success_title',
            field=models.CharField(default='Vielen Dank für Ihren Beitrag', help_text='An optional success title to show when the form has validation errors', max_length=64, null=True, verbose_name='Success Title'),
        ),
    ]
