# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0004_baseform_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseform',
            name='error_message',
            field=models.CharField(blank=True, help_text='An optional error message to show when the form has validation errors', max_length=255),
        ),
    ]
