# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import wagtailstreamforms.models.form


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0007_baseform_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseform',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=models.SET(wagtailstreamforms.models.form.get_default_form_content_type), related_name='streamforms', to='contenttypes.ContentType', verbose_name='content type'),
            preserve_default=False,
        ),
    ]
