# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0008_baseform_content_type_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailform',
            name='exclude_form_data',
            field=models.BooleanField(default=True, help_text='Exclude form submission data from email'),
        ),
    ]
