# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtailstreamforms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0008_baseform_content_type_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseform',
            name='add_recaptcha',
            field=models.BooleanField(default=False, help_text='Add a reCapcha field to the form.', verbose_name='add recaptcha'),
        ),
        migrations.AlterField(
            model_name='baseform',
            name='error_message',
            field=models.CharField(blank=True, help_text='An optional error message to show when the form has validation errors', max_length=255, verbose_name='error message'),
        ),
        migrations.AlterField(
            model_name='baseform',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='baseform',
            name='post_redirect_page',
            field=models.ForeignKey(blank=True, help_text='The page to redirect to after a successful submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='post redirect page'),
        ),
        migrations.AlterField(
            model_name='baseform',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='Used to identify the form in template tags', max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='baseform',
            name='store_submission',
            field=models.BooleanField(default=False, verbose_name='store submission'),
        ),
        migrations.AlterField(
            model_name='baseform',
            name='submit_button_text',
            field=models.CharField(default='Submit', max_length=100, verbose_name='submit button text'),
        ),
        migrations.AlterField(
            model_name='baseform',
            name='success_message',
            field=models.CharField(blank=True, help_text='An optional success message to show when the form has been successfully submitted', max_length=255, verbose_name='success message'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='fail_silently',
            field=models.BooleanField(default=True, verbose_name='fail silently'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='from_address',
            field=models.EmailField(max_length=254, verbose_name='from address'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='to_addresses',
            field=wagtailstreamforms.fields.MultiEmailField(help_text='Add one email per line', verbose_name='to addresses'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='form',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='wagtailstreamforms.BaseForm', verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='regex_validator',
            field=models.ForeignKey(blank=True, help_text="Applicable only for the field type 'regex validated field'.", null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailstreamforms.RegexFieldValidator', verbose_name='regex validator'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailstreamforms.BaseForm', verbose_name='form data'),
        ),
        migrations.AlterField(
            model_name='regexfieldvalidator',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='regexfieldvalidator',
            name='error_message',
            field=models.CharField(max_length=255, verbose_name='error message'),
        ),
        migrations.AlterField(
            model_name='regexfieldvalidator',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='regexfieldvalidator',
            name='regex',
            field=models.TextField(verbose_name='regex'),
        ),
    ]
