# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0008_baseform_content_type_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='custom_css_class',
            field=models.CharField(blank=True, help_text='A custom css class you can use in the template to target each form field.', max_length=255),
        ),
    ]
