# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0009_auto_20180130_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailstreamforms.BaseForm', verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form_data',
            field=models.TextField(verbose_name='form data'),
        ),
    ]
