# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import wagtailstreamforms.conf


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0011_auto_20180130_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseform',
            name='template_name',
            field=models.CharField(choices=wagtailstreamforms.conf.get_setting('FORM_TEMPLATES'), max_length=255, verbose_name='Template'),
        ),
    ]
